# Dependencies
markdown:         redcarpet
highlighter:      rouge
encoding:         utf-8

permalink: /theme/:title

# Setup
title:            WoBootstrap
tagline:          'Bootstrap Themes & Templates'
description:      'A collection of <strong>free</strong> CSS3, HTML5 & WordPress themes, templates, and plugins built using <a href="http://getbootstrap.com/">Bootstrap</a> and released under the <a href="http://en.wikipedia.org/wiki/MIT_License">MIT license</a> license.'
url:              http://wobootstrap.com
baseurl:          /

paginate:         6
