# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /theme/:title
relative_permalinks: true

# Setup
title:            WoBootstrap
tagline:          'Bootstrap Themes & Templates'
description:      'A collection of <strong>free</strong> CSS3, HTML5 & WordPress themes, templates, and plugins built using <a href="http://getbootstrap.com/">Bootstrap</a> and released under the <a href="http://en.wikipedia.org/wiki/MIT_License">MIT license</a> license.'
url:              http://wobootstrap.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
